name: Fuzz Selected Files
on: [push]
jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r KubeSec/KubeSec-master/requirements.txt
    - name: Run fuzz and save crash errors
      run: |
        python3 fuzz.py > output.log 2>&1 > output.log
