name: Fuzz Selected Files
on: [push]
jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
  
    - name: Upgrade pip, setuptools, wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install -r KubeSec/KubeSec-master/requirements.txt
        python -m pip install --index-url https://software.repos.intel.com/python/pypi --extra-index-url https://pypi.org/simple mkl_fft
    
    - name: Run fuzz and save crash errors
      run: |
        python3 KubeSec/KubeSec-master/fuzz.py > output.log 2>&1
        
    - name: Show fuzz output
      run: |
        cat output.log
